fix forkserver fuzzer
- use root dir to store current input
- report stats correctly
- add simple test for CI

diff --git a/fuzzers/baby/baby_forkserver/Justfile b/fuzzers/baby/baby_forkserver/Justfile
--- a/fuzzers/baby/baby_forkserver/Justfile
+++ b/fuzzers/baby/baby_forkserver/Justfile
@@ -4,4 +4,25 @@ FUZZER_NAME := "baby_forkserver"
 build:
     cargo build --profile {{ PROFILE }}
 
-test: build
+target:
+    afl-cc program.c -o program
+
+test: build target
+    #!/bin/bash
+    set -eu
+
+    timeout 15s {{ FUZZER }} ./program seeds/seed || true
+
+    STATS_FILE="./workdir/worker_0/fuzzer_stats"
+    if [ ! -f "$STATS_FILE" ]; then
+        echo "baby_forkserver: Stats file not found at $STATS_FILE"
+        exit 1
+    fi
+
+    OBJECTIVE=$(jq '.objective' "$STATS_FILE")
+    if [ "$OBJECTIVE" -eq 0 ]; then
+        echo "baby_forkserver: Fuzzer did not find any objective (stats: $STATS_FILE)"
+        exit 1
+    else
+        echo "baby_forkserver: Found $OBJECTIVE objective(s)."
+    fi
