saner Justfile

diff --git a/fuzzers/binary_only/frida_libpng/Justfile b/fuzzers/binary_only/frida_libpng/Justfile
--- a/fuzzers/binary_only/frida_libpng/Justfile
+++ b/fuzzers/binary_only/frida_libpng/Justfile
@@ -29,13 +29,20 @@ run: build harness
 test: build harness
     #!/bin/bash
 
-    rm -rf libafl_unix_shmem_server || true
-    timeout 30s {{ FUZZER }} -F LLVMFuzzerTestOneInput -H ./libpng-harness.so -l ./libpng-harness.so | tee fuzz_stdout.log 2>/dev/null || true
-    if grep -qa "corpus: 70" fuzz_stdout.log; then
-        echo "Fuzzer is working"
-    else
-        echo "Fuzzer does not generate any testcases or any crashes"
+    timeout 30s {{ FUZZER }} -F LLVMFuzzerTestOneInput -H ./libpng-harness.so -l ./libpng-harness.so 2>/dev/null || true
+    STATS_FILE="./workdir/worker_0/fuzzer_stats"
+
+    if [ ! -f "$STATS_FILE" ]; then
+        echo "libpng: Stats file not found at $STATS_FILE"
         exit 1
+    fi
+
+    CORPUS=$(jq '.corpus' "$STATS_FILE")
+    if [ "$CORPUS" -lt 100 ]; then
+        echo "sqlite: Fuzzer did not find more than 100 new interesting inputs (stats: $STATS_FILE, corpus found: $CORPUS)"
+        exit 1
+    else
+        echo "sqlite: Found $CORPUS new interesting input(s). success."
     fi
 
 clean:
