move rt handle stuff to dedicated file.
- add restart function to rt handle
- properly test sqlite
- fully working type inference
- timer can be given to launcher
- controller exposes workdir
- web stuff uses workdir properly
- better gitignore

diff --git a/fuzzers/inprocess/sqlite/Justfile b/fuzzers/inprocess/sqlite/Justfile
--- a/fuzzers/inprocess/sqlite/Justfile
+++ b/fuzzers/inprocess/sqlite/Justfile
@@ -5,3 +5,21 @@ build:
     ./build.sh {{ PROFILE }}
 
 test: build
+    #!/bin/bash
+    set -eu
+
+    timeout 20s ./ossfuzz
+
+    STATS_FILE="./workdir/worker_0/fuzzer_stats"
+    if [ ! -f "$STATS_FILE" ]; then
+        echo "sqlite: Stats file not found at $STATS_FILE"
+        exit 1
+    fi
+
+    OBJECTIVE=$(jq '.' "$STATS_FILE")
+    if [ "$OBJECTIVE" -eq 0 ]; then
+        echo "sqlite: Fuzzer did not find any objective (stats: $STATS_FILE)"
+        exit 1
+    else
+        echo "sqlite: Found $OBJECTIVE objective(s)."
+    fi
